'use client'

import React, { createContext, useContext, useState, useEffect, ReactNode, useMemo } from 'react'

type Language = 'uk' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  uk: {
    'nav.home': 'Головна',
    'nav.about': 'Про нас',
    'nav.news': 'Новини',
    'nav.events': 'Заходи',
    'nav.fundraisers': 'Збори',
    'nav.audience': 'Аудиторія',
    'nav.mvv': 'Місія та цінності',
    'nav.activities': 'Напрями',
    'nav.contact': 'Контакти',
    'nav.register': 'Реєстрація',
    'nav.login': 'Увійти',
    'nav.logout': 'Вийти',
    'nav.cabinet': 'Кабінет',
    'nav.donate': 'Допомогти',
    'hero.title': 'Благодійна організація',
    'hero.subtitle': '«Благодійний фонд «ПЛЮС ПУЛЬС»',
    'hero.description': 'Офіційний публічний інструмент Фонду для забезпечення довіри, прозорості та ефективної комунікації. Недержавна, неприбуткова благодійна організація, що діє відповідно до законодавства України',
    'hero.donate': 'Допомогти зараз',
    'hero.learn': 'Дізнатися більше',
    'about.title': 'Про організацію',
    'about.description': 'Благодійний фонд «ПЛЮС ПУЛЬС» — це професійна благодійна організація, що працює відповідно до найвищих стандартів прозорості та відповідальності',
    'about.fullName': 'Повна назва',
    'about.fullNameValue': 'Благодійна організація «Благодійний фонд «ПЛЮС ПУЛЬС»',
    'about.shortName': 'Скорочена назва',
    'about.shortNameValue': 'БО БФ «ПЛЮС ПУЛЬС»',
    'about.location': 'Місцезнаходження',
    'about.locationValue': 'Україна, Київська область, м. Українка',
    'about.president': 'Керівник / Президент Фонду',
    'about.presidentValue': 'Золотухіна Анастасія Андріївна',
    'about.status': 'Юридичний статус',
    'about.statusValue': 'Недержавна, неприбуткова благодійна організація, що діє відповідно до законодавства України. Форма: Благодійний фонд.',
    'activities.title': 'Основні напрями діяльності',
    'activities.description': 'Сайт чітко і структуровано відображає всі статутні напрями діяльності Фонду з можливістю подальшого розширення.',
    'activities.expandNote': 'Детальні описи програм і проєктів буде додано в наступних оновленнях.',
    'activities.directions.defense': 'Сприяння обороноздатності та мобілізаційній готовності',
    'activities.directions.emergency': 'Захист населення у надзвичайних ситуаціях',
    'activities.directions.education': 'Освіта',
    'activities.directions.health': 'Охорона здоров’я',
    'activities.directions.poverty': 'Соціальний захист і подолання бідності',
    'activities.directions.warAffected': 'Допомога постраждалим від війни, катастроф, конфліктів',
    'activities.directions.idp': 'Допомога біженцям та ВПО',
    'activities.directions.ecology': 'Екологія та захист довкілля',
    'activities.directions.humanRights': 'Права людини',
    'activities.directions.cultureScienceSport': 'Культура, наука, спорт',
    'activities.directions.communitiesIntl': 'Розвиток громад та міжнародна співпраця',

    'programsPreview.title': 'Актуальні програми / збори',
    'programsPreview.description':
      'Актуальні збори фонду з прозорими цілями та відображенням зібраних коштів. Детальніше та підтримати — на сторінці «Допомогти».',
    'programsPreview.ctaPrograms': 'Перейти до програм',
    'programsPreview.ctaDonate': 'Задонатити',
    'programsPreview.emptyFundraisers': 'Наразі немає активних зборів.',

    'newsPreview.title': 'Останні новини',
    'newsPreview.description': 'Новини фонду, звіти з подій, кампанії та інші оновлення.',
    'newsPreview.ctaAll': 'Усі новини',
    'newsPreview.empty': 'Поки немає опублікованих новин.',

    'trust.title': 'Блок довіри',
    'trust.description': 'Документи та звітність — критично важливі для довіри донорів і партнерів. Тут ми публікуємо ключові підтвердження прозорості.',
    'trust.items.statute': 'Статут',
    'trust.items.statuteNote': 'PDF для завантаження буде додано (розділ “Звітність і прозорість”).',
    'trust.items.reporting': 'Звітність',
    'trust.items.reportingNote': 'Фінансові звіти, використання коштів, джерела надходжень.',
    'trust.items.nonprofit': 'Неприбутковість',
    'trust.items.nonprofitNote': 'Підтвердження неприбуткового статусу та реєстраційні документи.',
    'trust.cta': 'Перейти до звітності',
    'donate.title': 'Ваша підтримка важлива',
    'donate.description': 'Кожна гривня, кожна хвилина вашого часу - це крок до кращого майбутнього. Ваші донати допомагають нам реалізовувати благодійні програми та допомагати тим, хто цього найбільше потребує. Разом ми можемо більше!',
    'donate.formTitle': 'Зробити внесок',
    'donate.subtitle': 'Підтримайте наші програми',
    'donate.note': 'Деталі для перерахування коштів будуть додані найближчим часом. Ми забезпечуємо повну прозорість використання всіх отриманих коштів.',
    'donate.onetime': 'Одноразовий внесок',
    'donate.regular': 'Регулярна підтримка',
    'donate.individuals': 'Фізичні особи',
    'donate.legal': 'Юридичні особи',
    'donate.international': 'Міжнародні партнери',
    'contact.title': 'Контакти',
    'contact.address': 'Адреса',
    'contact.president': 'Керівник',
    'contact.feedbackTitle': 'Ваші побажання та пропозиції',
    'contact.feedbackLead':
      'Поділіться думками, як нам покращити сайт і роботу фонду. Ми уважно читаємо кожне повідомлення. Поля з іменем та електронною поштою необов’язкові, але вони допоможуть відповісти вам за потреби.',
    'contact.feedbackName': 'Ім’я (необов’язково)',
    'contact.feedbackEmail': 'Електронна пошта (необов’язково)',
    'contact.feedbackMessage': 'Повідомлення',
    'contact.feedbackMessagePh': 'Опишіть ідею, зауваження або подяку… (щонайменше 10 символів)',
    'contact.feedbackSubmit': 'Надіслати',
    'contact.feedbackPending': 'Надсилання…',
    'contact.feedbackSuccess': 'Дякуємо! Ваше повідомлення збережено.',
    'contact.feedbackErrorValidation': 'Перевірте поля: текст — від 10 до 4000 символів; електронна пошта має бути коректною, якщо ви її вказали.',
    'contact.feedbackErrorGeneric': 'Не вдалося надіслати. Спробуйте пізніше.',
    'footer.navigation': 'Навігація',
    'footer.contact': 'Контакти',
    'footer.rights': 'Всі права захищені.',
    'register.title': 'Реєстрація',
    'register.subtitle': 'Створіть обліковий запис, щоб згодом організовувати волонтерські заходи та долучатися до них.',
    'register.email': 'Електронна пошта',
    'register.name': 'Ім’я (необов’язково)',
    'register.password': 'Пароль',
    'register.confirmPassword': 'Підтвердження пароля',
    'register.submit': 'Зареєструватися',
    'register.pending': 'Реєстрація…',
    'register.errorDuplicate': 'Користувач з такою електронною поштою вже зареєстрований.',
    'register.errorGeneric': 'Щось пішло не так. Спробуйте пізніше.',
    'register.errorValidation': 'Перевірте правильність заповнення полів.',
    'register.errorMismatch': 'Паролі не збігаються.',
    'register.errorShort': 'Пароль має містити щонайменше 8 символів.',
    'register.errorEmail': 'Некоректна адреса електронної пошти.',
    'register.linkLogin': 'Вже є акаунт? Увійти',
    'login.title': 'Вхід',
    'login.subtitle': 'Уведіть електронну пошту та пароль облікового запису.',
    'login.email': 'Електронна пошта',
    'login.password': 'Пароль',
    'login.submit': 'Увійти',
    'login.pending': 'Вхід…',
    'login.linkRegister': 'Немає акаунту? Зареєструватися',
    'login.errorInvalid': 'Невірна електронна пошта або пароль.',
    'login.errorEmail': 'Некоректна адреса електронної пошти.',
    'login.errorGeneric': 'Не вдалося увійти. Спробуйте пізніше.',
    'login.modalClose': 'Закрити',
    'cabinet.pageTitle': 'Особистий кабінет',
    'cabinet.pageLead': 'Оновіть фото, розкажіть про себе та вкажіть контакти — це допоможе координувати волонтерську участь.',
    'cabinet.statsAria': 'Статистика користувача',
    'cabinet.statsHosted': 'Організовано заходів',
    'cabinet.statsParticipated': 'Участь у заходах',
    'cabinet.statsHostedAria': 'Організовано заходів: {count}',
    'cabinet.statsParticipatedAria': 'Участь у заходах: {count}',
    'cabinet.displayName': 'Як до вас звертатись',
    'cabinet.bio': 'Про себе',
    'cabinet.bioPlaceholder': 'Коротко: досвід, інтереси, чим готові допомогти…',
    'cabinet.bioLimit': 'До 1500 символів.',
    'cabinet.phone': 'Телефон',
    'cabinet.phoneHint': 'Введіть 9 цифр номера без префікса (наприклад 501234567). Зберігається як +380…',
    'cabinet.phoneDigitsAria': 'Дев’ять цифр мобільного після +380',
    'cabinet.city': 'Місто / населений пункт',
    'cabinet.avatar': 'Фото профілю',
    'cabinet.avatarHint': 'JPEG, PNG або WebP, до 2 МБ. Нове фото замінить попереднє.',
    'cabinet.save': 'Зберегти зміни',
    'cabinet.saving': 'Збереження…',
    'cabinet.saved': 'Зміни збережено.',
    'cabinet.errorUnauth': 'Потрібно увійти в акаунт.',
    'cabinet.errorFilesize': 'Файл завеликий (максимум 2 МБ).',
    'cabinet.errorFiletype': 'Дозволені лише зображення JPEG, PNG або WebP.',
    'cabinet.errorBio': 'Опис не може бути довшим за 1500 символів.',
    'cabinet.errorPhone': 'Телефон: введіть рівно 9 цифр після +380 або залиште поле порожнім.',
    'cabinet.errorGeneric': 'Не вдалося зберегти. Спробуйте ще раз.',
    'events.pageTitle': 'Волонтерські заходи',
    'events.pageLead': 'Тут збираються оголошення про зустрічі та волонтерські ініціативи. Увійдіть у акаунт, щоб створити свій захід.',
    'events.pageLeadAuthed': 'Тут збираються оголошення про зустрічі та волонтерські ініціативи. Новий захід можна додати кнопкою праворуч.',
    'events.createSideCta': 'Створити захід',
    'events.asideLabel': 'Дії з заходами',
    'events.backToList': '← До списку заходів',
    'events.newPageNav': 'Навігація сторінки створення заходу',
    'events.loginToCreate': 'Щоб створювати заходи, увійдіть у свій акаунт (кнопка «Увійти» у меню).',
    'events.createHeading': 'Створити захід',
    'events.createLead': 'Заповніть дані — їх побачать усі відвідувачі сторінки «Заходи».',
    'events.fieldTitle': 'Назва заходу',
    'events.fieldReason': 'Мета / причина зустрічі',
    'events.fieldReasonPh': 'Наприклад: збір допомоги, планування волонтерської акції…',
    'events.fieldDescription': 'Опис (необов’язково)',
    'events.fieldDescriptionPh': 'Деталі, що взяти з собою, контакт організатора в описі не дублюйте — видно ваше ім’я з профілю.',
    'events.fieldStartsAt': 'Дата і час',
    'events.fieldLocation': 'Локація (адреса або місце)',
    'events.fieldMapLocation': 'Локація на карті (місто Київ)',
    'events.errorMapPin': 'Оберіть точку на карті (клацніть по карті).',
    'events.mapHintKyiv':
      'Карта доступна лише в межах міста Київ. Клацніть, щоб поставити точку зустрічі; маркер можна перетягувати. Текст адреси для списку формується автоматично після збереження.',
    'events.mapOutsideKyiv': 'Точку можна ставити лише на території Києва.',
    'events.errorOutsideKyiv': 'Локація події має бути всередині міста Київ.',
    'events.mapClear': 'Прибрати точку з карти',
    'events.openOnMap': 'Відкрити на карті',
    'events.submit': 'Опублікувати захід',
    'events.saving': 'Публікація…',
    'events.created': 'Захід опубліковано.',
    'events.pendingModeration':
      'Заявку надіслано адміністратору на перевірку. Після рішення захід з’явиться у списку або зміни будуть застосовані. Ви отримаєте результат після модерації.',
    'events.unauth': 'Потрібно увійти в акаунт.',
    'events.errorValidation': 'Перевірте коректність полів (назва, дата, локація).',
    'events.errorPast': 'Оберіть дату та час у майбутньому.',
    'events.aiReject.off_topic':
      'Текст заходу не відповідає тематиці добровільної або суспільно корисної діяльності. Уточіть формулювання.',
    'events.aiReject.nonsense':
      'Опис виглядає несерйозним або нерелевантним. Коротко поясніть, кому допомогає захід та що робитимуть учасники.',
    'events.aiReject.spam': 'Формат схожий на спам або сторонню рекламу. Змініть назву чи опис на конкретний волонтерський запит.',
    'events.aiReject.harmful': 'Цей текст не може бути опублікований з етичних або безпекових міркувань.',
    'events.aiReject.unclear':
      'Недостатньо зрозуміло, що це допустимий волонтерський захід. Додайте конкретику: що, для кого та де відбувається.',
    'events.aiReject.other': 'Автоматична перевірка не затвердила опис. Переробіть назву, мету та опис або зверніться до адміністрації.',
    'events.aiUnavailable':
      'Не налаштовано ключ Google Gemini для перевірки тексту заходів. Додайте GEMINI_API_KEY у змінних середовища.',
    'events.aiTimeout': 'Автоматична перевірка не встигла завершитися. Спробуйте ще раз за кілька хвилин.',
    'events.aiError': 'Сервіс перевірки тимчасово недоступний. Повторіть спробу пізніше.',
    'events.errorGeneric': 'Не вдалося створити захід. Спробуйте пізніше.',
    'events.errorSave': 'Не вдалося зберегти зміни. Спробуйте пізніше.',
    'events.errorForbidden': 'Немає прав на цю дію або захід не знайдено.',
    'events.edit': 'Редагувати',
    'events.archive': 'Завершити',
    'events.archiveConfirm': 'Завершити (архівувати) цей захід? Після завершення він потрапить до архіву.',
    'events.archiving': 'Завершення…',
    'events.archiveError': 'Не вдалося завершити захід.',
    'events.delete': 'Видалити',
    'events.deleteConfirm': 'Видалити цей захід? Цю дію не можна скасувати.',
    'events.deleting': 'Видалення…',
    'events.deleteError': 'Не вдалося видалити захід.',
    'events.editHeading': 'Редагувати захід',
    'events.editLead': 'Оновіть дані — зміни одразу з’являться у списку заходів.',
    'events.editPageNav': 'Навігація редагування заходу',
    'events.updateSubmit': 'Зберегти зміни',
    'events.updateSaving': 'Збереження…',
    'events.updated': 'Зміни збережено.',
    'events.fieldMaxParticipants': 'Бажана кількість учасників (необов’язково)',
    'events.fieldMaxParticipantsPh': 'Без обмеження — залиште порожнім',
    'events.errorMaxBelowJoined': 'Ліміт не може бути меншим за кількість уже доєднаних учасників.',
    'events.join': 'Доєднатися',
    'events.joinPending': 'Доєднання…',
    'events.joinErrorHost': 'Організатор не може доєднатися до власної події.',
    'events.joinErrorFull': 'Усі місця зайняті.',
    'events.joinErrorAlready': 'Ви вже доєднані до цієї події.',
    'events.joinErrorArchived': 'Цей захід уже завершено та знаходиться в архіві.',
    'events.joinErrorGeneric': 'Не вдалося доєднатися. Спробуйте ще раз.',
    'events.leave': 'Покинути подію',
    'events.leavePending': 'Вихід…',
    'events.leaveErrorNotMember': 'Ви не берете участі в цій події.',
    'events.leaveErrorGeneric': 'Не вдалося вийти з події. Спробуйте ще раз.',
    'events.listHeading': 'Усі заходи',
    'events.archivedHeading': 'Архівні заходи ({count})',
    'events.archivedBadge': 'Архів',
    'events.filterAria': 'Пошук і фільтри заходів',
    'events.searchLabel': 'Пошук',
    'events.searchPlaceholder': 'Назва, опис, місце, організатор…',
    'events.filterDistrict': 'Район Києва',
    'events.filterDistrictAll': 'Усі райони',
    'events.filterDateFrom': 'Дата від',
    'events.filterDateTo': 'Дата до',
    'events.filterHint': 'Пошук працює за назвою, описом, місцем та організатором. Район визначається за координатами або адресою.',
    'events.filterClear': 'Скинути дати',
    'events.filterClearAll': 'Скинути всі фільтри',
    'events.filterNoResults': 'За обраними критеріями заходів не знайдено. Змініть пошук, район або дати.',
    'events.filterCount': 'Показано: {shown} з {total}',
    'events.empty': 'Поки немає жодного заходу. Створіть перший — якщо ви увійшли в акаунт.',
    'events.host': 'Організатор',
    'events.participants': 'учасників',
    'events.detailBack': 'Усі заходи',
    'events.detailNavAria': 'Навігація до списку заходів',
    'events.chatHeading': 'Чат заходу',
    'events.chatEmpty': 'Повідомлень ще немає — напишіть перше. Тут спілкуються лише учасники цього заходу та організатор.',
    'events.chatArchivedHint': 'Захід завершено та знаходиться в архіві. Надсилання повідомлень у чат вимкнено.',
    'events.chatPlaceholder': 'Ваше повідомлення…',
    'events.chatSend': 'Надіслати',
    'events.chatHintLogin': 'Увійдіть, щоб доєднатися до заходу або переглянути опис. Після входу ви зможете приєднатися й користуватися чатом.',
    'events.chatHintJoin': 'Доєднайтеся до заходу, щоб відкрити чат з організатором та іншими учасниками.',
    'events.chatErrorValidation': 'Порожнє або надто довге повідомлення (макс. 2000 символів).',
    'events.chatErrorForbidden': 'Немає доступу до цього чату.',
    'events.chatErrorArchived': 'Цей захід уже завершено, тому чат закрито.',
    'events.chatErrorGeneric': 'Не вдалося надіслати повідомлення.',
    'events.memberFallback': 'Учасник',
    'events.openParticipantCard': 'Відкрити картку учасника: {name}',
    'events.participantBadgeHost': 'Організатор',
    'events.participantCity': 'Місто',
    'events.participantPhone': 'Телефон',
    'events.participantBio': 'Про себе',
    'events.participantStatsAria': 'Статистика учасника',
    'events.participantStatsHosted': 'Організовано',
    'events.participantStatsParticipated': 'Участь',
    'events.closePanel': 'Закрити',
    'events.you': '(ви)',
    'mission.title': 'Мета створення сайту',
    'mission.description': 'Сайт створюється як офіційний публічний інструмент Фонду, що має забезпечити довіру, прозорість та ефективну комунікацію',
    'mission.trust': 'Довіра',
    'mission.trustDesc': 'Забезпечення довіри з боку благодійників, партнерів та громадськості через відкритість та професійність',
    'mission.transparency': 'Прозорість',
    'mission.transparencyDesc': 'Повна прозорість діяльності, фінансів, програм та звітності для всіх зацікавлених сторін',
    'mission.funding': 'Залучення коштів',
    'mission.fundingDesc': 'Прийом донатів від фізичних та юридичних осіб, включно з міжнародними партнерами',
    'mission.communication': 'Комунікація',
    'mission.communicationDesc': 'Ефективна комунікація з бенефіціарами, волонтерами, партнерами, державними та міжнародними структурами',
    'mission.information': 'Інформаційна діяльність',
    'mission.informationDesc': 'Популяризація цілей Фонду та інформування про нашу діяльність широкої громадськості',
    'transparency.title': 'Прозорість та звітність',
    'transparency.description': 'Ми забезпечуємо повну прозорість нашої діяльності та фінансової звітності',
    'transparency.reports': 'Публічна звітність',
    'transparency.reportsDesc': 'Регулярна публікація звітів про діяльність Фонду, використання коштів та досягнуті результати',
    'transparency.finances': 'Фінансова прозорість',
    'transparency.financesDesc': 'Повна інформація про надходження та витрати коштів. Публікація фінансових звітів',
    'transparency.programs': 'Прозорість програм',
    'transparency.programsDesc': 'Детальна інформація про реалізовані та поточні благодійні програми та проекти',
    'transparency.accountability': 'Відповідальність',
    'transparency.accountabilityDesc': 'Відповідальність перед благодійниками, партнерами та громадськістю за результати нашої роботи',

    'audience.title': 'Цільова аудиторія сайту',
    'audience.description': 'Ми будуємо комунікацію так, щоб кожна група могла швидко знайти потрібну інформацію: як допомогти, як співпрацювати або як отримати підтримку.',
    'audience.primary.title': 'Основна аудиторія',
    'audience.primary.donors': 'Благодійники (фізичні особи, бізнес, міжнародні донори)',
    'audience.primary.partners': 'Партнери (НДО, ініціативи, організації)',
    'audience.primary.volunteers': 'Волонтери',
    'audience.primary.beneficiaries': 'Бенефіціари (особи, які потребують допомоги)',
    'audience.secondary.title': 'Додаткова аудиторія',
    'audience.secondary.media': 'Журналісти та медіа',
    'audience.secondary.government': 'Державні та місцеві органи',
    'audience.secondary.internationalFunds': 'Міжнародні фонди та донорські програми',
    'audience.secondary.public': 'Загальна громадськість',

    'mvv.title': 'Місія, візія, цінності',
    'mvv.description': 'Фундамент нашої діяльності — чітка місія, амбітна візія та цінності, яких ми дотримуємося щодня.',
    'mvv.mission.title': 'Місія',
    'mvv.mission.text': 'Надання системної, адресної та ефективної благодійної допомоги задля збереження життя, здоров’я, безпеки людей та розвитку суспільства України в умовах мирного і воєнного часу.',
    'mvv.vision.title': 'Візія',
    'mvv.vision.text': 'Сильний, прозорий та відповідальний благодійний фонд, який об’єднує людей і ресурси для захисту, підтримки та розвитку України.',
    'mvv.values.title': 'Цінності',
    'mvv.values.legality': 'Законність',
    'mvv.values.transparency': 'Прозорість',
    'mvv.values.openness': 'Відкритість',
    'mvv.values.voluntariness': 'Добровільність',
    'mvv.values.humanity': 'Гуманність',
    'mvv.values.responsibility': 'Відповідальність',
    'mvv.values.dignity': 'Повага до людини та її гідності',

    'admin.dashboardTitle': 'Адмін-панель',
    'admin.tileNews': 'Новини',
    'admin.tileFundraisers': 'Збори',
    'admin.newsTitle': 'Новини',
    'admin.fundraisersTitle': 'Збори',
    'admin.create': 'Створити',
    'admin.edit': 'Редагувати',
    'admin.back': 'Назад',
    'admin.save': 'Зберегти',
    'admin.emptyNews': 'Поки немає записів.',
    'admin.emptyFundraisers': 'Поки немає зборів.',
    'admin.statusDraft': 'чернетка',
    'admin.statusPublished': 'опубліковано',
    'admin.statusArchived': 'архів',
    'admin.statusActive': 'активний',
    'admin.noTag': '—',
    'admin.newsNewTitle': 'Нова новина',
    'admin.newsEditTitle': 'Редагування новини',
    'admin.fundraiserNewTitle': 'Новий збір',
    'admin.fundraiserEditTitle': 'Редагування збору',
    'admin.fieldTitle': 'Заголовок',
    'admin.fieldSlug': 'Слаг (URL)',
    'admin.slugHint': 'Латиниця, цифри та дефіси. При збереженні нормалізується автоматично.',
    'admin.fieldExcerpt': 'Короткий опис (необов’язково)',
    'admin.fieldBody': 'Текст новини',
    'admin.fieldCover': 'Обкладинка',
    'admin.removeCover': 'Прибрати обкладинку',
    'admin.coverHint': 'JPEG, PNG або WebP, до 5 МБ.',
    'admin.fieldGallery': 'Галерея зображень',
    'admin.galleryUploadHint':
      'Оберіть один або кілька файлів (JPEG, PNG, WebP, до 5 МБ кожен). Після збереження вони з’являться в списку; під час редагування можна додати нові або видалити зайві.',
    'admin.remove': 'Видалити',
    'admin.fieldPublished': 'Опубліковано',
    'admin.fieldArchived': 'У архіві',
    'admin.fieldTag': 'Тег (необов’язково)',
    'admin.tagHint': 'Наприклад: Дрони',
    'admin.fieldDescription': 'Опис збору',
    'admin.fieldGoalUah': 'Цільова сума (₴)',
    'admin.fieldRaisedUah': 'Зібрано (₴)',
    'admin.errValidation': 'Перевірте поля форми.',
    'admin.errSlugConflict': 'Такий слаг уже використовується. Змініть слаг.',
    'admin.errUpload': 'Не вдалося завантажити файл.',
    'admin.errGeneric': 'Не вдалося зберегти. Спробуйте ще раз.',
    'admin.tileEvents': 'Заходи',
    'admin.tileFeedback': 'Побажання',
    'admin.feedbackTitle': 'Побажання та зворотний зв’язок',
    'admin.feedbackEmpty': 'Поки немає надісланих повідомлень.',
    'admin.feedbackFieldName': 'Ім’я',
    'admin.feedbackFieldEmail': 'Електронна пошта',
    'admin.feedbackFieldMessage': 'Текст повідомлення',
    'admin.eventsTitle': 'Заходи',
    'admin.eventsPendingHeading': 'На модерації (AI)',
    'admin.eventsPendingEmpty': 'Немає заявок на перевірку.',
    'admin.eventsPendingKindCreate': 'новий захід',
    'admin.eventsPendingKindEdit': 'редагування',
    'admin.eventsSourceAmbiguous': 'неоднозначно (AI)',
    'admin.eventsSourceService': 'збій перевірки',
    'admin.eventsApprove': 'Схвалити',
    'admin.eventsReject': 'Відхилити',
    'admin.eventsListHeading': 'Усі заходи',
    'admin.eventsListEmpty': 'Заходів немає.',
    'admin.eventsParticipants': 'учасн.',
    'admin.eventsOpen': 'Відкрити',
    'admin.eventsDelete': 'Видалити',
    'admin.eventsDeleteConfirm': 'Видалити цей захід? Учасники та повідомлення буде втрачено.',
    'admin.events.actionError': 'Не вдалося виконати дію.',
  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.news': 'News',
    'nav.events': 'Events',
    'nav.fundraisers': 'Fundraisers',
    'nav.audience': 'Audience',
    'nav.mvv': 'Mission & Values',
    'nav.activities': 'Directions',
    'nav.contact': 'Contact',
    'nav.register': 'Sign up',
    'nav.login': 'Log in',
    'nav.logout': 'Log out',
    'nav.cabinet': 'Account',
    'nav.donate': 'Donate',
    'hero.title': 'Charitable Organization',
    'hero.subtitle': '«Charity Fund PLUS PULSE»',
    'hero.description': 'Official public tool of the Fund to ensure trust, transparency and effective communication. Non-governmental, non-profit charitable organization operating in accordance with Ukrainian legislation',
    'hero.donate': 'Donate Now',
    'hero.learn': 'Learn More',
    'about.title': 'About the Organization',
    'about.description': 'Charity Fund "PLUS PULSE" is a professional charitable organization operating in accordance with the highest standards of transparency and accountability',
    'about.fullName': 'Full Name',
    'about.fullNameValue': 'Charitable Organization "Charity Fund PLUS PULSE"',
    'about.shortName': 'Short Name',
    'about.shortNameValue': 'CO CF "PLUS PULSE"',
    'about.location': 'Location',
    'about.locationValue': 'Ukraine, Kyiv region, Ukrainka city',
    'about.president': 'President',
    'about.presidentValue': 'Zolotukhina Anastasiia Andriivna',
    'about.status': 'Legal Status',
    'about.statusValue': 'Non-governmental, non-profit charitable organization operating in accordance with Ukrainian legislation. Form: Charity Fund.',
    'activities.title': 'Key Areas of Activity',
    'activities.description': 'The website clearly and structurally presents all statutory areas of the Fund’s work with the ability to expand over time.',
    'activities.expandNote': 'Detailed program and project descriptions will be added in the next updates.',
    'activities.directions.defense': 'Strengthening defense capability and mobilization readiness',
    'activities.directions.emergency': 'Protection of the population in emergencies',
    'activities.directions.education': 'Education',
    'activities.directions.health': 'Healthcare',
    'activities.directions.poverty': 'Social protection and poverty reduction',
    'activities.directions.warAffected': 'Support for people affected by war, disasters, and conflicts',
    'activities.directions.idp': 'Support for refugees and internally displaced persons (IDPs)',
    'activities.directions.ecology': 'Ecology and environmental protection',
    'activities.directions.humanRights': 'Human rights',
    'activities.directions.cultureScienceSport': 'Culture, science, sports',
    'activities.directions.communitiesIntl': 'Community development and international cooperation',

    'programsPreview.title': 'Active Programs / Fundraisers',
    'programsPreview.description':
      'Current fundraisers with transparent goals and progress. Learn more and donate on the Help page.',
    'programsPreview.ctaPrograms': 'Go to programs',
    'programsPreview.ctaDonate': 'Donate',
    'programsPreview.emptyFundraisers': 'No active fundraisers at the moment.',

    'newsPreview.title': 'Latest News',
    'newsPreview.description': 'Fund news, event reports, campaigns and other updates.',
    'newsPreview.ctaAll': 'All news',
    'newsPreview.empty': 'No published news yet.',

    'trust.title': 'Trust & Credibility',
    'trust.description': 'Documents and reporting are critical for donor confidence. Here we publish key proofs of transparency.',
    'trust.items.statute': 'Statute',
    'trust.items.statuteNote': 'A downloadable PDF will be added (see “Transparency & Reporting”).',
    'trust.items.reporting': 'Reporting',
    'trust.items.reportingNote': 'Financial reports, use of funds, sources of income.',
    'trust.items.nonprofit': 'Non-profit status',
    'trust.items.nonprofitNote': 'Proof of non-profit status and registration documents.',
    'trust.cta': 'Go to reporting',
    'donate.title': 'Your Support Matters',
    'donate.description': 'Every hryvnia, every minute of your time is a step towards a better future. Your donations help us implement charitable programs and help those who need it most. Together we can do more!',
    'donate.formTitle': 'Make a Donation',
    'donate.subtitle': 'Support our programs',
    'donate.note': 'Bank details for transfers will be added soon. We ensure full transparency in the use of all funds received.',
    'donate.onetime': 'One-time Donation',
    'donate.regular': 'Regular Support',
    'donate.individuals': 'Individuals',
    'donate.legal': 'Legal Entities',
    'donate.international': 'International Partners',
    'contact.title': 'Contact Us',
    'contact.address': 'Address',
    'contact.president': 'President',
    'contact.feedbackTitle': 'Suggestions and feedback',
    'contact.feedbackLead':
      'Tell us how we can improve the website and our work. We read every message. Name and email are optional but help us reply if needed.',
    'contact.feedbackName': 'Name (optional)',
    'contact.feedbackEmail': 'Email (optional)',
    'contact.feedbackMessage': 'Message',
    'contact.feedbackMessagePh': 'Share an idea, a concern, or thanks… (at least 10 characters)',
    'contact.feedbackSubmit': 'Send',
    'contact.feedbackPending': 'Sending…',
    'contact.feedbackSuccess': 'Thank you! Your message has been saved.',
    'contact.feedbackErrorValidation':
      'Please check the fields: message must be 10–4000 characters; if you enter an email, it must be valid.',
    'contact.feedbackErrorGeneric': 'Could not send your message. Please try again later.',
    'footer.navigation': 'Navigation',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'register.title': 'Sign up',
    'register.subtitle': 'Create an account to organize volunteer activities and join them later on.',
    'register.email': 'Email',
    'register.name': 'Name (optional)',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm password',
    'register.submit': 'Create account',
    'register.pending': 'Signing up…',
    'register.errorDuplicate': 'An account with this email already exists.',
    'register.errorGeneric': 'Something went wrong. Please try again later.',
    'register.errorValidation': 'Please check the form fields.',
    'register.errorMismatch': 'Passwords do not match.',
    'register.errorShort': 'Password must be at least 8 characters.',
    'register.errorEmail': 'Invalid email address.',
    'register.linkLogin': 'Already have an account? Log in',
    'login.title': 'Log in',
    'login.subtitle': 'Enter your email and password.',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Log in',
    'login.pending': 'Signing in…',
    'login.linkRegister': 'No account? Sign up',
    'login.errorInvalid': 'Invalid email or password.',
    'login.errorEmail': 'Invalid email address.',
    'login.errorGeneric': 'Could not sign in. Please try again later.',
    'login.modalClose': 'Close',
    'cabinet.pageTitle': 'Your account',
    'cabinet.pageLead': 'Add a photo, a short bio and contact details to help coordinate volunteer activities.',
    'cabinet.statsAria': 'User stats',
    'cabinet.statsHosted': 'Events organised',
    'cabinet.statsParticipated': 'Events joined',
    'cabinet.statsHostedAria': 'Events organised: {count}',
    'cabinet.statsParticipatedAria': 'Events joined: {count}',
    'cabinet.displayName': 'Display name',
    'cabinet.bio': 'About you',
    'cabinet.bioPlaceholder': 'Briefly: experience, interests, how you’d like to help…',
    'cabinet.bioLimit': 'Up to 1500 characters.',
    'cabinet.phone': 'Phone',
    'cabinet.phoneHint': 'Enter 9 digits without the prefix (e.g. 501234567). Stored as +380…',
    'cabinet.phoneDigitsAria': 'Nine digits of mobile number after +380',
    'cabinet.city': 'City / locality',
    'cabinet.avatar': 'Profile photo',
    'cabinet.avatarHint': 'JPEG, PNG or WebP, up to 2 MB. A new photo replaces the previous one.',
    'cabinet.save': 'Save changes',
    'cabinet.saving': 'Saving…',
    'cabinet.saved': 'Changes saved.',
    'cabinet.errorUnauth': 'You need to sign in.',
    'cabinet.errorFilesize': 'File is too large (max 2 MB).',
    'cabinet.errorFiletype': 'Only JPEG, PNG or WebP images are allowed.',
    'cabinet.errorBio': 'Description cannot exceed 1500 characters.',
    'cabinet.errorPhone': 'Phone: enter exactly 9 digits after +380, or leave the field empty.',
    'cabinet.errorGeneric': 'Could not save. Please try again.',
    'events.pageTitle': 'Volunteer events',
    'events.pageLead': 'Meetings and volunteer initiatives posted here. Sign in to create your own event.',
    'events.pageLeadAuthed': 'Meetings and volunteer initiatives posted here. You can add a new event using the button on the right.',
    'events.createSideCta': 'Create event',
    'events.asideLabel': 'Event actions',
    'events.backToList': '← Back to events',
    'events.newPageNav': 'Create event page navigation',
    'events.loginToCreate': 'To create events, sign in to your account (the “Log in” button in the menu).',
    'events.createHeading': 'Create an event',
    'events.createLead': 'These details are visible to everyone on this page.',
    'events.fieldTitle': 'Event title',
    'events.fieldReason': 'Purpose / reason for meeting',
    'events.fieldReasonPh': 'e.g. aid collection, planning a volunteer action…',
    'events.fieldDescription': 'Description (optional)',
    'events.fieldDescriptionPh': 'Details, what to bring — your name from profile is shown as organiser.',
    'events.fieldStartsAt': 'Date and time',
    'events.fieldLocation': 'Location (address or place)',
    'events.fieldMapLocation': 'Location on map (Kyiv city only)',
    'events.errorMapPin': 'Pick a point on the map (click the map).',
    'events.mapHintKyiv':
      'The map is limited to Kyiv city. Click to set the meeting point; you can drag the marker. The address text for the list is generated automatically when you save.',
    'events.mapOutsideKyiv': 'You can only place a marker within Kyiv city.',
    'events.errorOutsideKyiv': 'The event location must be inside Kyiv city.',
    'events.mapClear': 'Remove map pin',
    'events.openOnMap': 'Open on map',
    'events.submit': 'Publish event',
    'events.saving': 'Publishing…',
    'events.created': 'Event published.',
    'events.pendingModeration':
      'Your request was sent to an administrator for review. The event will appear in the list or your edits will apply after moderation.',
    'events.unauth': 'You need to sign in.',
    'events.errorValidation': 'Please check the fields (title, date, location).',
    'events.errorPast': 'Pick a date and time in the future.',
    'events.aiReject.off_topic':
      'This does not appear to describe a volunteer or public-benefit activity. Refocus the wording on a real volunteering use case.',
    'events.aiReject.nonsense':
      'The text looks frivolous or unclear. Explain who you help and what participants will actually do.',
    'events.aiReject.spam':
      'The content resembles spam or off-topic promotion. Replace it with a specific volunteer-focused description.',
    'events.aiReject.harmful':
      'This content cannot be published for safety or ethics reasons.',
    'events.aiReject.unclear':
      'We could not confirm this is an appropriate volunteer activity. Add concrete details about what happens and where.',
    'events.aiReject.other':
      'Automatic review did not approve the text. Rewrite the title, purpose and description or contact the site admins.',
    'events.aiUnavailable':
      'Google Gemini API key is not configured for event text checks. Set GEMINI_API_KEY in the server environment.',
    'events.aiTimeout': 'Automatic review timed out. Please try again in a few minutes.',
    'events.aiError': 'The review service is temporarily unavailable. Please try again later.',
    'events.errorGeneric': 'Could not create the event. Please try again later.',
    'events.errorSave': 'Could not save changes. Please try again later.',
    'events.errorForbidden': 'You do not have permission or the event was not found.',
    'events.edit': 'Edit',
    'events.archive': 'Finish',
    'events.archiveConfirm': 'Finish (archive) this event? It will be moved to the archive.',
    'events.archiving': 'Finishing…',
    'events.archiveError': 'Could not finish the event.',
    'events.delete': 'Delete',
    'events.deleteConfirm': 'Delete this event? This cannot be undone.',
    'events.deleting': 'Deleting…',
    'events.deleteError': 'Could not delete the event.',
    'events.editHeading': 'Edit event',
    'events.editLead': 'Update the details — changes appear in the events list right away.',
    'events.editPageNav': 'Edit event page navigation',
    'events.updateSubmit': 'Save changes',
    'events.updateSaving': 'Saving…',
    'events.updated': 'Changes saved.',
    'events.fieldMaxParticipants': 'Desired number of participants (optional)',
    'events.fieldMaxParticipantsPh': 'Leave empty for no limit',
    'events.errorMaxBelowJoined': 'The limit cannot be lower than the number of participants already joined.',
    'events.join': 'Join',
    'events.joinPending': 'Joining…',
    'events.joinErrorHost': 'The organiser cannot join their own event.',
    'events.joinErrorFull': 'All spots are taken.',
    'events.joinErrorAlready': 'You are already part of this event.',
    'events.joinErrorArchived': 'This event has already finished and is in the archive.',
    'events.joinErrorGeneric': 'Could not join. Please try again.',
    'events.leave': 'Leave event',
    'events.leavePending': 'Leaving…',
    'events.leaveErrorNotMember': 'You are not participating in this event.',
    'events.leaveErrorGeneric': 'Could not leave the event. Please try again.',
    'events.listHeading': 'All events',
    'events.archivedHeading': 'Archived events ({count})',
    'events.archivedBadge': 'Archived',
    'events.filterAria': 'Search and filter events',
    'events.searchLabel': 'Search',
    'events.searchPlaceholder': 'Title, description, location, host…',
    'events.filterDistrict': 'Kyiv district',
    'events.filterDistrictAll': 'All districts',
    'events.filterDateFrom': 'From date',
    'events.filterDateTo': 'To date',
    'events.filterHint': 'Search matches title, description, location, and host. District is inferred from coordinates or address.',
    'events.filterClear': 'Clear dates',
    'events.filterClearAll': 'Clear all filters',
    'events.filterNoResults': 'No events match your filters. Try a different search, district, or dates.',
    'events.filterCount': 'Showing: {shown} of {total}',
    'events.empty': 'No events yet. Create the first one after signing in.',
    'events.host': 'Organiser',
    'events.participants': 'participants',
    'events.detailBack': 'All events',
    'events.detailNavAria': 'Navigation to events list',
    'events.chatHeading': 'Event chat',
    'events.chatEmpty': 'No messages yet — say hello. Only participants in this event and the organiser can use this chat.',
    'events.chatArchivedHint': 'This event is finished and archived. Sending messages is disabled.',
    'events.chatPlaceholder': 'Your message…',
    'events.chatSend': 'Send',
    'events.chatHintLogin': 'Sign in to join an event or read the details. After signing in you can join and use the chat.',
    'events.chatHintJoin': 'Join the event to open the chat with the organiser and other participants.',
    'events.chatErrorValidation': 'Message cannot be empty and must be at most 2000 characters.',
    'events.chatErrorForbidden': 'You do not have access to this chat.',
    'events.chatErrorArchived': 'This event is finished, so the chat is closed.',
    'events.chatErrorGeneric': 'Could not send the message.',
    'events.memberFallback': 'Participant',
    'events.openParticipantCard': 'Open participant card: {name}',
    'events.participantBadgeHost': 'Organiser',
    'events.participantCity': 'City',
    'events.participantPhone': 'Phone',
    'events.participantBio': 'About',
    'events.participantStatsAria': 'Participant stats',
    'events.participantStatsHosted': 'Organised',
    'events.participantStatsParticipated': 'Joined',
    'events.closePanel': 'Close',
    'events.you': '(you)',
    'mission.title': 'Website Purpose',
    'mission.description': 'The website is created as an official public tool of the Fund to ensure trust, transparency and effective communication',
    'mission.trust': 'Trust',
    'mission.trustDesc': 'Building trust among donors, partners and the public through openness and professionalism',
    'mission.transparency': 'Transparency',
    'mission.transparencyDesc': 'Full transparency of activities, finances, programs and reporting for all stakeholders',
    'mission.funding': 'Fundraising',
    'mission.fundingDesc': 'Accepting donations from individuals and legal entities, including international partners',
    'mission.communication': 'Communication',
    'mission.communicationDesc': 'Effective communication with beneficiaries, volunteers, partners, government and international structures',
    'mission.information': 'Information Activities',
    'mission.informationDesc': 'Promoting the Fund\'s goals and informing the general public about our activities',
    'transparency.title': 'Transparency and Accountability',
    'transparency.description': 'We ensure full transparency of our activities and financial reporting',
    'transparency.reports': 'Public Reporting',
    'transparency.reportsDesc': 'Regular publication of reports on the Fund\'s activities, use of funds and achieved results',
    'transparency.finances': 'Financial Transparency',
    'transparency.financesDesc': 'Complete information on income and expenses. Publication of financial reports',
    'transparency.programs': 'Program Transparency',
    'transparency.programsDesc': 'Detailed information about implemented and current charitable programs and projects',
    'transparency.accountability': 'Accountability',
    'transparency.accountabilityDesc': 'Accountability to donors, partners and the public for the results of our work',

    'audience.title': 'Target Audience',
    'audience.description': 'We structure information so every group can quickly find what they need: how to donate, collaborate, volunteer, or request support.',
    'audience.primary.title': 'Primary Audience',
    'audience.primary.donors': 'Donors (individuals, business, international donors)',
    'audience.primary.partners': 'Partners (NGOs, initiatives, organizations)',
    'audience.primary.volunteers': 'Volunteers',
    'audience.primary.beneficiaries': 'Beneficiaries (people who need support)',
    'audience.secondary.title': 'Secondary Audience',
    'audience.secondary.media': 'Journalists and media',
    'audience.secondary.government': 'State and local authorities',
    'audience.secondary.internationalFunds': 'International funds and donor programs',
    'audience.secondary.public': 'General public',

    'mvv.title': 'Mission, Vision, Values',
    'mvv.description': 'Our work is grounded in a clear mission, an ambitious vision, and values we follow every day.',
    'mvv.mission.title': 'Mission',
    'mvv.mission.text': 'Providing systematic, targeted and effective charitable assistance to preserve life, health and safety, and to support the development of Ukrainian society in both peacetime and wartime.',
    'mvv.vision.title': 'Vision',
    'mvv.vision.text': 'A strong, transparent and accountable charity fund that unites people and resources to protect, support and develop Ukraine.',
    'mvv.values.title': 'Values',
    'mvv.values.legality': 'Legality',
    'mvv.values.transparency': 'Transparency',
    'mvv.values.openness': 'Openness',
    'mvv.values.voluntariness': 'Voluntariness',
    'mvv.values.humanity': 'Humanity',
    'mvv.values.responsibility': 'Accountability',
    'mvv.values.dignity': 'Respect for human dignity',

    'admin.dashboardTitle': 'Admin',
    'admin.tileNews': 'News',
    'admin.tileFundraisers': 'Fundraisers',
    'admin.newsTitle': 'News',
    'admin.fundraisersTitle': 'Fundraisers',
    'admin.create': 'Create',
    'admin.edit': 'Edit',
    'admin.back': 'Back',
    'admin.save': 'Save',
    'admin.emptyNews': 'No posts yet.',
    'admin.emptyFundraisers': 'No fundraisers yet.',
    'admin.statusDraft': 'draft',
    'admin.statusPublished': 'published',
    'admin.statusArchived': 'archived',
    'admin.statusActive': 'active',
    'admin.noTag': '—',
    'admin.newsNewTitle': 'New post',
    'admin.newsEditTitle': 'Edit post',
    'admin.fundraiserNewTitle': 'New fundraiser',
    'admin.fundraiserEditTitle': 'Edit fundraiser',
    'admin.fieldTitle': 'Title',
    'admin.fieldSlug': 'Slug (URL)',
    'admin.slugHint': 'Latin letters, numbers and dashes. Normalized on save.',
    'admin.fieldExcerpt': 'Excerpt (optional)',
    'admin.fieldBody': 'Body',
    'admin.fieldCover': 'Cover image',
    'admin.removeCover': 'Remove cover',
    'admin.coverHint': 'JPEG, PNG or WebP, up to 5 MB.',
    'admin.fieldGallery': 'Gallery images',
    'admin.galleryUploadHint':
      'Choose one or more files (JPEG, PNG, WebP, up to 5 MB each). After saving they appear in the list; when editing you can add more or remove items.',
    'admin.remove': 'Remove',
    'admin.fieldPublished': 'Published',
    'admin.fieldArchived': 'Archived',
    'admin.fieldTag': 'Tag (optional)',
    'admin.tagHint': 'Example: Drones',
    'admin.fieldDescription': 'Description',
    'admin.fieldGoalUah': 'Goal amount (UAH)',
    'admin.fieldRaisedUah': 'Raised amount (UAH)',
    'admin.errValidation': 'Please check the fields.',
    'admin.errSlugConflict': 'This slug is already taken.',
    'admin.errUpload': 'Upload failed.',
    'admin.errGeneric': 'Could not save.',
    'admin.tileEvents': 'Events',
    'admin.tileFeedback': 'Feedback',
    'admin.feedbackTitle': 'Feedback and suggestions',
    'admin.feedbackEmpty': 'No messages yet.',
    'admin.feedbackFieldName': 'Name',
    'admin.feedbackFieldEmail': 'Email',
    'admin.feedbackFieldMessage': 'Message',
    'admin.eventsTitle': 'Events',
    'admin.eventsPendingHeading': 'Pending review (AI)',
    'admin.eventsPendingEmpty': 'No pending requests.',
    'admin.eventsPendingKindCreate': 'new event',
    'admin.eventsPendingKindEdit': 'edit',
    'admin.eventsSourceAmbiguous': 'ambiguous (AI)',
    'admin.eventsSourceService': 'check failed',
    'admin.eventsApprove': 'Approve',
    'admin.eventsReject': 'Reject',
    'admin.eventsListHeading': 'All events',
    'admin.eventsListEmpty': 'No events yet.',
    'admin.eventsParticipants': 'partic.',
    'admin.eventsOpen': 'Open',
    'admin.eventsDelete': 'Delete',
    'admin.eventsDeleteConfirm': 'Delete this event? Participants and messages will be lost.',
    'admin.events.actionError': 'Action failed.',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Завжди починаємо з 'uk' для SSR, потім оновлюємо після монтування
  const [language, setLanguageState] = useState<Language>('uk')
  const [isMounted, setIsMounted] = useState(false)

  useEffect(() => {
    setIsMounted(true)
    // Завантажуємо мову з localStorage тільки після монтування
    try {
      if (typeof window !== 'undefined' && window.localStorage) {
        const savedLang = localStorage.getItem('language') as Language
        if (savedLang && (savedLang === 'uk' || savedLang === 'en')) {
          setLanguageState(savedLang)
        }
      }
    } catch (error) {
      // Ігноруємо помилки
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    try {
      if (typeof window !== 'undefined' && window.localStorage) {
        localStorage.setItem('language', lang)
      }
    } catch (error) {
      // Ігноруємо помилки
    }
  }

  const t = useMemo(() => {
    return (key: string): string => {
      return translations[language]?.[key] || key
    }
  }, [language])

  const value = useMemo(() => ({
    language,
    setLanguage,
    t,
  }), [language, t])

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
